import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import { mkdir, readFile } from 'node:fs/promises';

const modulePath = process.env.PLAYWRIGHT_MODULE || 'C:/Users/Ariel/.gemini/antigravity/worktrees/SIA-Enrollment-System--main/enrollment-ux-design-audit/node_modules/@playwright/test/index.mjs';
const { chromium } = await import(pathToFileURL(modulePath).href);
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 }, colorScheme: 'light' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:4381');
  assert.equal(await page.locator('h1').textContent(), 'Ariel Casipe');
  assert((await page.locator('.wordmark').textContent()).startsWith('ariel'));
  assert.equal(await page.locator('a[href="https://www.instagram.com/ariellcsp/"]').count(), 1);
  await page.waitForFunction(() => document.querySelector('.portrait')?.naturalWidth > 0);
  await page.waitForFunction(() => getComputedStyle(document.querySelector('.intro-copy')).opacity === '1');
  assert(await page.locator('.intro-copy').evaluate(node => node.classList.contains('is-visible')));
  await page.waitForFunction(() => document.querySelector('.portrait-wrap').classList.contains('is-visible'));
  assert.equal(await page.locator('.portrait-wrap').evaluate(node => getComputedStyle(node).animationIterationCount), 'infinite');
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click({ force: true });
  assert.equal(await page.locator('.portrait-wrap').evaluate(node => getComputedStyle(node).animationPlayState), 'paused');
  await page.getByRole('button', { name: 'Resume motion', exact: true }).focus();
  await page.keyboard.press('Space');
  assert.equal(await page.locator('.portrait-wrap').getAttribute('aria-pressed'), 'false');
  await page.evaluate(() => scrollTo({ top: document.documentElement.scrollHeight, behavior: 'instant' }));
  await page.waitForFunction(() => !document.querySelector('.intro-copy').classList.contains('is-visible'));
  await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }));
  await page.waitForFunction(() => document.querySelector('.intro-copy').classList.contains('is-visible'));
  await page.waitForFunction(() => getComputedStyle(document.querySelector('.intro-copy')).opacity === '1');
  assert.deepEqual(await page.locator('.dock a').allTextContents(), ['Me', 'Projects', 'Stack', 'Resources', 'GitHub']);
  assert.equal(await page.locator('.project-card').count(), 4);
  assert.equal(await page.locator('[data-status="upcoming"]').count(), 0);
  assert.equal(await page.locator('[data-resources] a').count(), 5);
  assert.equal(await page.locator('[data-status="upcoming"] button, [data-status="upcoming"] a').count(), 0);
  assert.equal(await page.locator('[data-project-id="enrollment"] .repository').getAttribute('href'), 'https://github.com/hil9-pya/enrollmentsystem');
  assert.equal(await page.locator('[data-project-id="enrollment"] .live-site').getAttribute('href'), 'https://sia-enrollment.kesug.com/');
  assert.equal(await page.locator('[data-project-id="kickcraft"] .repository').getAttribute('href'), 'https://github.com/hil9-pya/kickcraft');
  assert.equal(await page.locator('[data-project-id="can-it-fit"] .repository').getAttribute('href'), 'https://github.com/hil9-pya/can-it-fit');
  assert.equal(await page.locator('[data-project-id="can-it-fit"] .slide-dots button').count(), 3);
  assert.equal(await page.locator('[data-project-id="memory-pins"] .repository').getAttribute('href'), 'https://github.com/hil9-pya/memory-pins');
  assert.equal(await page.locator('[data-project-id="memory-pins"] .slide-dots button').count(), 3);
  assert((await page.locator('[data-stack]').textContent()).includes('TypeScript'));
  assert(!(await page.locator('[data-stack]').textContent()).includes('Playwright'));
  assert.deepEqual(await page.locator('main > section').evaluateAll(nodes => nodes.map(node => node.id)), ['me', 'projects', 'stack', 'resources', 'github']);
  const dimensions = await page.locator('.project-card').evaluateAll(nodes => nodes.map(node => {
    const { width, x, y } = node.getBoundingClientRect(); return { width, x, y };
  }));
  assert(dimensions.every(item => Math.abs(item.width - dimensions[0].width) < 1));
  assert.equal(dimensions[0].y, dimensions[1].y);
  assert.equal(dimensions[2].y, dimensions[3].y);
  assert(dimensions[2].y > dimensions[0].y);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert(await page.locator('[data-contributions]').textContent());
  assert.deepEqual((await page.locator('.stack-group').first().locator('.stack-chip').allTextContents()).slice(0, 3), ['HTML', 'CSS', 'JavaScript']);
  assert(!(await page.locator('[data-stack]').textContent()).includes('model-viewer'));
  assert.equal(await page.locator('.contribution-cell.level-4>span').first().evaluate(node => getComputedStyle(node).borderRadius), '1px');
  await mkdir('output', { recursive: true });
  await page.screenshot({ path: 'output/desktop-light.png', fullPage: true });
  await page.screenshot({ path: 'output/viewport-light.png' });
  if (!process.argv.includes('--layout')) {
    const activity = page.locator('[data-contributions]');
    assert.equal(await activity.locator('details').count(), 1, 'Contribution dates/counts need an accessible alternative');
    await activity.locator('summary').click();
    const activityData = JSON.parse(await readFile('assets/contributions.json', 'utf8'));
    const lastDay = activityData.days.at(-1);
    const firstActiveDay = activityData.days.find(day => day.count > 0);
    assert.equal(await activity.locator('tbody tr').first().locator('td').first().textContent(), firstActiveDay.date);
    assert.equal(await activity.getByRole('cell', { name: lastDay.date, exact: true }).count(), 1);
    assert((await activity.ariaSnapshot()).includes(lastDay.date), 'Daily dates must be exposed to assistive technology');
    await activity.locator('summary').click();
    const enrollment = page.locator('.project-card[data-project-id="enrollment"]');
    const kickcraft = page.locator('.project-card[data-project-id="kickcraft"]');
    const firstCaption = await enrollment.locator('.slide-caption').textContent();
    const kickCaption = await kickcraft.locator('.slide-caption').textContent();
    await enrollment.getByRole('button', { name: 'Previous screenshot', exact: true }).click();
    assert.equal(await enrollment.locator('.slide-caption').textContent(), 'Learning portal');
    await enrollment.getByRole('button', { name: 'Next screenshot', exact: true }).click();
    assert.equal(await enrollment.locator('.slide-caption').textContent(), firstCaption);
    await enrollment.getByRole('button', { name: 'Show screenshot 2', exact: true }).click();
    assert.equal(await enrollment.locator('.slide-caption').textContent(), 'Enrollment gateway');
    assert.equal(await kickcraft.locator('.slide-caption').textContent(), kickCaption);
    const trigger = enrollment.getByRole('button', { name: 'Open Enrollment System gallery', exact: true });
    await trigger.click();
    const dialog = page.locator('#gallery-dialog');
    assert(await dialog.isVisible());
    await page.screenshot({ path: 'output/gallery-dialog.png' });
    await page.keyboard.press('ArrowRight');
    assert((await dialog.locator('[data-dialog-caption]').textContent()).includes('Learning portal'));
    await page.keyboard.press('Escape');
    assert(!(await dialog.isVisible()));
    assert(await trigger.evaluate(node => node === document.activeElement));
    const third = page.locator('[data-project-id="can-it-fit"]');
    await third.getByRole('button', { name: 'Show screenshot 2', exact: true }).click();
    await third.locator('.gallery-open').click();
    assert((await dialog.locator('[data-dialog-caption]').textContent()).includes('What-if preview'));
    await page.waitForFunction(() => document.querySelector('#gallery-dialog img').naturalWidth > 0);
    await page.keyboard.press('Escape');
    const fourth = page.locator('[data-project-id="memory-pins"]');
    await fourth.getByRole('button', { name: 'Show screenshot 3', exact: true }).click();
    await fourth.locator('.gallery-open').click();
    assert((await dialog.locator('[data-dialog-caption]').textContent()).includes('Memory collection'));
    await page.waitForFunction(() => document.querySelector('#gallery-dialog img').naturalWidth > 0);
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Change theme', exact: true }).click();
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
    await page.reload();
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
    await page.screenshot({ path: 'output/desktop-dark.png', fullPage: true });
    await page.evaluate(() => scrollTo(0, 0));
    await page.waitForTimeout(500);
    await page.screenshot({ path: 'output/viewport-dark.png' });
    await page.locator('.dock a[href="#resources"]').click();
    await page.waitForFunction(() => document.querySelector('.dock a[href="#resources"]').getAttribute('aria-current') === 'location');
    await page.evaluate(() => scrollTo(0, document.documentElement.scrollHeight));
    await page.waitForTimeout(800);
    const dock = await page.locator('.dock').boundingBox();
    const footerLink = await page.locator('footer a').boundingBox();
    assert(footerLink.y + footerLink.height < dock.y, 'Dock covers footer destination');
    await page.screenshot({ path: 'output/desktop-bottom.png' });
    const systemContext = await browser.newContext({ viewport: { width: 1920, height: 1080 }, colorScheme: 'dark', reducedMotion: 'reduce' });
    const systemPage = await systemContext.newPage();
    await systemPage.addInitScript(() => {
      Storage.prototype.getItem = () => { throw new Error('Storage blocked'); };
      Storage.prototype.setItem = () => { throw new Error('Storage blocked'); };
    });
    await systemPage.route('**/assets/contributions.json', route => route.abort());
    await systemPage.goto('http://127.0.0.1:4381');
    assert.equal(await systemPage.locator('html').getAttribute('data-theme'), 'light');
    assert((await systemPage.locator('[data-contributions]').textContent()).includes('unavailable'));
    await systemPage.getByRole('button', { name: 'Change theme', exact: true }).click();
    assert.equal(await systemPage.locator('html').getAttribute('data-theme'), 'dark');
    assert.equal(await systemPage.locator('html').evaluate(node => getComputedStyle(node).scrollBehavior), 'auto');
    assert.equal(await systemPage.locator('.dock a').first().evaluate(node => getComputedStyle(node).transitionDuration), '0s');
    assert.equal(await systemPage.locator('.reveal').count(), 0, 'Reduced motion must skip scroll reveals');
    assert.equal(await systemPage.locator('.portrait-wrap').evaluate(node => getComputedStyle(node).animationName), 'none');
    await systemContext.close();
    const emptyActivity = await browser.newPage();
    await emptyActivity.route('**/assets/contributions.json', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ ...activityData, days: activityData.days.map(day => ({ ...day, count: 0, level: 0 })) }) }));
    await emptyActivity.goto('http://127.0.0.1:4381');
    assert.equal(await emptyActivity.locator('.activity-details tbody').textContent(), 'No contributions recorded in this period.');
    await emptyActivity.close();
    const content = await readFile('content.mjs', 'utf8');
    for (const variant of ['single', 'empty', 'broken']) {
      const scenario = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
      await scenario.route('**/content.mjs', route => route.fulfill({ contentType: 'application/javascript', body: content + `\nprojects[0].screenshots = ${variant === 'single' ? 'projects[0].screenshots.slice(0,1)' : variant === 'empty' ? '[]' : '[{src:"assets/projects/missing.png",alt:"Missing preview",caption:"Broken image"}]'};` }));
      await scenario.goto('http://127.0.0.1:4381');
      const card = scenario.locator('.project-card[data-project-id="enrollment"]');
      assert.equal(await card.locator('.slide-arrow, .slide-dots button').count(), 0);
      if (variant !== 'single') {
        await card.locator('.image-fallback').waitFor({ state: 'visible' });
        if (variant === 'empty') assert(await card.locator('.gallery-open').isDisabled());
      }
      await scenario.close();
    }
    console.log('PASS: independent galleries, wraparound, dots, keyboard dialog/focus, theme persistence, light default, storage/data/image fallbacks, dock clearance, reduced motion');
  }
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await mobile.goto('http://127.0.0.1:4381');
  await mobile.waitForSelector('.contribution-scroll');
  assert(await mobile.locator('.contribution-scroll').evaluate(node =>
    node.scrollLeft > 0 && Math.abs(node.scrollWidth - node.clientWidth - node.scrollLeft) <= 1));
  await mobile.locator('.contribution-scroll').evaluate(node => { node.scrollLeft = 0; });
  assert.equal(await mobile.locator('.contribution-scroll').evaluate(node => node.scrollLeft), 0);
  await mobile.close();
  assert.deepEqual(errors, []);
  console.log('PASS: desktop layout, four equal project slots, five resources, honest destinations');
} finally {
  await browser.close();
}
